In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[9.2755e-39, 1.0561e-38, 6.2449e-39],
        [9.0000e-39, 1.0102e-38, 9.8265e-39],
        [7.5306e-39, 1.1112e-38, 5.9694e-39],
        [8.9082e-39, 1.0194e-38, 9.1837e-39],
        [4.6837e-39, 9.9184e-39, 9.0000e-39]])


In [3]:
x = torch.rand(5, 3)  #construct a random initialized matrix
print(x)

tensor([[0.3968, 0.0455, 0.8537],
        [0.3338, 0.1728, 0.8700],
        [0.8814, 0.9918, 0.9434],
        [0.5732, 0.9150, 0.4507],
        [0.4385, 0.3125, 0.8593]])


In [4]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.3, 3])
print(x)

tensor([5.3000, 3.0000])


In [6]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [7]:
x = torch.randn_like(x, dtype = torch.float)
print(x)

tensor([[-0.5168,  0.3186,  0.2894],
        [ 0.4744, -0.5462, -0.5831],
        [ 0.0346, -1.2920,  0.2575],
        [-0.6192,  0.4941,  1.6218],
        [-0.1107, -1.3739,  0.8283]])


In [8]:
print(x.size())

torch.Size([5, 3])


In [9]:
y = torch.rand(5, 3)
print(x+y)

tensor([[-0.4606,  0.6410,  0.4281],
        [ 1.2956, -0.1216, -0.3188],
        [ 0.4220, -0.6875,  1.1559],
        [-0.2764,  1.2692,  2.0143],
        [ 0.4350, -0.4314,  1.0409]])


In [10]:
print(torch.add(x,y))

tensor([[-0.4606,  0.6410,  0.4281],
        [ 1.2956, -0.1216, -0.3188],
        [ 0.4220, -0.6875,  1.1559],
        [-0.2764,  1.2692,  2.0143],
        [ 0.4350, -0.4314,  1.0409]])


In [11]:
result = torch.empty(5, 3)
torch.add(x,y, out=result)
print(result)

tensor([[-0.4606,  0.6410,  0.4281],
        [ 1.2956, -0.1216, -0.3188],
        [ 0.4220, -0.6875,  1.1559],
        [-0.2764,  1.2692,  2.0143],
        [ 0.4350, -0.4314,  1.0409]])


In [12]:
y.add_(x)

tensor([[-0.4606,  0.6410,  0.4281],
        [ 1.2956, -0.1216, -0.3188],
        [ 0.4220, -0.6875,  1.1559],
        [-0.2764,  1.2692,  2.0143],
        [ 0.4350, -0.4314,  1.0409]])

In [13]:
print(x[:, 1])

tensor([ 0.3186, -0.5462, -1.2920,  0.4941, -1.3739])


In [16]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8)

print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [17]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.0565])
-1.0564887523651123


In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)

array([2., 2., 2., 2., 2.])